---
language: python

env:
  global:
    - PACKER_VERSION=1.5.1
    - TERRAFORM_VERSION=0.12.18

before_install:
  - curl -sLo /tmp/packer_linux_amd64.zip https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
  - curl -sLo /tmp/terraform_linux_amd64.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip

install:
  - unzip '/tmp/*_linux_amd64.zip' -d ~/bin/
  - export PATH=~/bin:$PATH
  - pip install ansible

before_script:
  - packer --version
  - terraform --version
  - ansible --version

script:
  - cd ./packer && packer validate parity.json
  - cd ./terraform/global && terraform validate 