---

  - name: Install prerequisites
    apt:
      name: "{{ parity_prerequisites }}"
      update_cache: yes
  
  - name: Download Parity binary
    get_url:
      url: "{{ parity_url }}"
      dest: "{{ parity_dir }}/parity"
      checksum: "{{ parity_checksum }}"
      owner: "{{ parity_user }}"
      group: "{{ parity_group }}"
      mode: 0700
  
  - name: Copy parity scripts
    template:
      src: "{{ item }}.j2"
      dest: "{{ parity_dir }}/{{ item }}"
      owner: "{{ parity_user }}"
      group: "{{ parity_group }}"
      mode: 0500
    with_items:
      - parity-init.sh

  - name: Manage Parity config file
    template:
      src: config.toml.j2
      dest: "{{ parity_dir }}/config.toml"
      owner: "{{ parity_user }}"
      group: "{{ parity_group }}"
      mode: 0400
    notify: restart parity
     