---
  - name: Create group {{ parity_group }}
    group:
      name: "{{ parity_group }}"

  - name: Create user {{ parity_user }}
    user: 
      name: "{{ parity_user }}"
      group: "{{ parity_group }}"
      home: "{{ parity_dir }}"
      create_home: no

  - name: Create directory {{ parity_dir }}
    file:
      path: "{{ parity_dir }}"
      owner: "{{ parity_user }}"
      group: "{{ parity_group }}"
      state: directory
      mode: 0700