---

- hosts: parity
  gather_facts: yes
  become: yes

  pre_tasks:
    - name: Dist Upgrade
      include: tasks/dist_upgrade.yaml  

  roles:
    - role: ffrizzo.metricbeat
      metricbeat_version: 7.5.0
      metricbeat_enabled: no

    - role: ffrizzo.aws-inspector
      awsagent_enabled: no    

    - role: ffrizzo.parity
      parity_rpc_allowed_hosts: '["all"]'
      parity_ws_allowed_hosts: '["all"]'

    - role: geerlingguy.nginx
      nginx_remove_default_vhost: yes
      nginx_upstreams:
        - name: parityrpc
          servers:
            - "localhost:8545"
          keepalive: 256
      nginx_vhosts:
        - listen: "80"
          server_name: "parity.ffrizzo.com"
          extra_parameters: |
              location @app {
                proxy_http_version  1.1;
                proxy_set_header    Connection         "";
                proxy_set_header    Host               $host;
                proxy_set_header    X-Real-IP          $remote_addr;
                proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
                proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;

                proxy_connect_timeout      90;
                proxy_send_timeout         90;
                proxy_read_timeout         90;
                proxy_buffer_size          128k;
                proxy_buffers              4 256k;
                proxy_busy_buffers_size    256k;
                proxy_temp_file_write_size 256k;
                proxy_max_temp_file_size   0;

                add_header Cache-Control  "no-cache no-store must-revalidate";
                add_header Pragma         no-cache;
                add_header Expires        0;

                proxy_pass http://parityrpc;
                add_header Strict-Transport-Security "max-age=31536000; includeSubDomains;";
              }
              location /rpc {
                try_files $uri $uri/ @app;
              }

              location /ws {
                try_files $uri $uri/ @app;
              }
