---
# defaults file for ffrizzo.parity
parity_mirror: https://releases.parity.io
parity_platform: x86_64-unknown-linux-gnu
parity_version: 2.6.8
parity_checksum: sha256:299f928503cb3b8d44d95a0f592e32358542ec854842c277e3eeaee2a3478a28

parity_prerequisites:
 - build-essential 
 - cmake 
 - libudev-dev

parity_dir: /opt/parity
parity_user: parity
parity_group: parity

parity_service: parity.service
parity_exec_base: "{{parity_dir}}/parity --config={{ parity_dir }}/config.toml"

parity_log_file: "{{parity_dir}}/parity.log"

parity_rpc_port: 8545
parity_rpc_address: 127.0.0.1
parity_rpc_allowed_hosts: '["none"]'
parity_ws_port: 8546
parity_ws_address: 127.0.0.1
parity_ws_allowed_hosts: '["none"]'
parity_ws_origins: '["parity://*"]'

parity_chain: ethereum

parity_mode: active

parity_cache: 2048